require_relative 'models/user'
require_relative '../scripts/snapshot'
require_relative 'models/tweet'
require_relative 'models/non_bro'
require_relative 'models/rule_model'
require_relative 'models/rule'
